### PR TITLE
Improves Java html presentation

### PR DESCRIPTION
**Pull request by otaviojava**
This PR has two features:

* Define alphabetically order to source
* Define highlight text to the source code

### CODE REVIEW

**Comment by Crell** [comment]
https://pr-25-rpbm4di-rjify4yjcwxaa.eu-3.platformsh.site/java - Gives me a 502. :frowning: 

The PR itself looks fine to me visually, but the built image seems unhappy.

**Comment by otaviojava** [comment]
@Crell please try now:
https://pr-25-rpbm4di-rjify4yjcwxaa.eu-3.platformsh.site/java

**Comment by chadwcarlson** [comment]
New link works, looks great @otaviojava

**Comment by Crell** [comment]
We should consider coloring the output on all the examples if we're going to do so here.  But I like this improvement, so merging.

Also, I missed when we even added the index page for Java.  Score. :-)

**Pull request merged**
